# frozen_string_literal: true

# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Untitled' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'untitled' do
    @driver.get('http://localhost:3000')
    @driver.find_element(:link_text, 'Sign In').click
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:css, '.column').click
    @driver.find_element(:id, 'user_email').send_keys('user1@mail.com')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('user1@mail.com')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:id, 'post_post').send_keys('Post')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '.box:nth-child(2) .level-item:nth-child(1) .fa').click
    @driver.find_element(:link_text, 'Edit').click
    @driver.find_element(:id, 'post_post').click
    @driver.find_element(:id, 'post_post').send_keys('Hello World!')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Back').click
    @driver.find_element(:css, '.box:nth-child(2) .level-item:nth-child(1) .fa').click
    @driver.find_element(:css, '.button_to > .button').click
    @driver.find_element(:link_text, 'Logout').click
    @driver.close
  end
end
